yaml
name: eventBackend cicd
on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'
    - name: Run install dependencies 
      run: npm install
    # - name: Run typescript
    #   run: npx tsc
    - name: running server
      run: npm run dev