name: CI/CD Pipeline
on:
  push:
    branches: [new]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
      # Step 4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # - name: Build Application and Run unit Test
      #   run: python app.py & pytest
  continuous-deployment:
    runs-on: ubuntu-latest
    name: appleboy/ssh-action test
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: root
          key: ${{ secrets.AWS_SECRET_KEY_PEM }}
          script: echo hellow  
  # continuous-deployment:
  #   runs-on: ubuntu-latest
  #   needs: [continuous-integration]
  #   if: github.ref == 'refs/heads/new'
  #   steps:
  #     # Step 1
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with: 
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ap-south-1
  #     # Step 2
  #     - name: Create CodeDeploy Deployment
  #       id: deploy
  #       run: |
  #         aws deploy create-deployment \
  #           --application-name eventsBackendDeployment \
  #           --deployment-group-name trial \
  #           --deployment-config-name CodeDeployDefault.AllAtOnce \
  #           --no-ignore-application-stop-failure \
  #           --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
